/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recipesearch;

/**
 *
 * @author missAMTL
 */
public class StepbyStepPanel extends javax.swing.JPanel {

    /**
     * Creates new form IngredientPanel
     */
    public StepbyStepPanel() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StepbyStepPanel = new javax.swing.JPanel();
        descriptionLabel = new javax.swing.JLabel();

        StepbyStepPanel.setBackground(new java.awt.Color(255, 255, 255));
        StepbyStepPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Step by Step"));

        descriptionLabel.setText("jLabel2");

        javax.swing.GroupLayout StepbyStepPanelLayout = new javax.swing.GroupLayout(StepbyStepPanel);
        StepbyStepPanel.setLayout(StepbyStepPanelLayout);
        StepbyStepPanelLayout.setHorizontalGroup(
            StepbyStepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StepbyStepPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descriptionLabel)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        StepbyStepPanelLayout.setVerticalGroup(
            StepbyStepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StepbyStepPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descriptionLabel)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(StepbyStepPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(StepbyStepPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void setDescription(String des){
        descriptionLabel.setText(des);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StepbyStepPanel;
    private javax.swing.JLabel descriptionLabel;
    // End of variables declaration//GEN-END:variables
}
